import type { Metadata } from "next";
import "./globals.css";
import { ConvexClientProvider } from "@/components/ConvexClientProvider";
import { ConvexAuthNextjsServerProvider } from "@convex-dev/auth/nextjs/server";
// Supports weights 100-900
import '@fontsource-variable/noto-serif';
// Supports weights 200-900
import '@fontsource-variable/source-code-pro';
// Supports weights 100-900
import '@fontsource-variable/inter';
import { Toaster } from "@/components/ui/toaster";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<ConvexAuthNextjsServerProvider>
			<html lang="en">
				<body className="">
					<ConvexClientProvider>
							{children}
					</ConvexClientProvider>
					<Toaster />
				</body>
			</html>
		</ConvexAuthNextjsServerProvider>
	);
}
